
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.102:3306/sell?characterEncoding=UTF-8&userSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
  port: 9090
